version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:1.34.1
    steps:
      - checkout
      - run:
          name: "Install Dependencies and Build"
          command: |
            rustup install nightly
            rustup default nightly
            cargo build
      - run:
          name: "Run Test Suite"
          command: |
            cargo test

